/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RangeSliderChangeEvent } from "./components/range-slider-touch/range-slider-touch";
export { RangeSliderChangeEvent } from "./components/range-slider-touch/range-slider-touch";
export namespace Components {
    interface ScrollSafeSlider {
        "disabled"?: boolean;
        "max": number;
        "min": number;
        /**
          * Specifies the value granularity.
         */
        "step": number;
        /**
          * Tick mark values to display along the track.
         */
        "ticks": number[];
        /**
          * Long press time in milliseconds.
         */
        "time": number;
        "value": number;
    }
}
export interface ScrollSafeSliderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLScrollSafeSliderElement;
}
declare global {
    interface HTMLScrollSafeSliderElementEventMap {
        "sliderInput": RangeSliderChangeEvent;
        "sliderChange": RangeSliderChangeEvent;
    }
    interface HTMLScrollSafeSliderElement extends Components.ScrollSafeSlider, HTMLStencilElement {
        addEventListener<K extends keyof HTMLScrollSafeSliderElementEventMap>(type: K, listener: (this: HTMLScrollSafeSliderElement, ev: ScrollSafeSliderCustomEvent<HTMLScrollSafeSliderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLScrollSafeSliderElementEventMap>(type: K, listener: (this: HTMLScrollSafeSliderElement, ev: ScrollSafeSliderCustomEvent<HTMLScrollSafeSliderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLScrollSafeSliderElement: {
        prototype: HTMLScrollSafeSliderElement;
        new (): HTMLScrollSafeSliderElement;
    };
    interface HTMLElementTagNameMap {
        "scroll-safe-slider": HTMLScrollSafeSliderElement;
    }
}
declare namespace LocalJSX {
    interface ScrollSafeSlider {
        "disabled"?: boolean;
        "max"?: number;
        "min"?: number;
        /**
          * Emits value only on release and changed.
         */
        "onSliderChange"?: (event: ScrollSafeSliderCustomEvent<RangeSliderChangeEvent>) => void;
        /**
          * Emits value on move, press and release.
         */
        "onSliderInput"?: (event: ScrollSafeSliderCustomEvent<RangeSliderChangeEvent>) => void;
        /**
          * Specifies the value granularity.
         */
        "step"?: number;
        /**
          * Tick mark values to display along the track.
         */
        "ticks"?: number[];
        /**
          * Long press time in milliseconds.
         */
        "time"?: number;
        "value"?: number;
    }
    interface IntrinsicElements {
        "scroll-safe-slider": ScrollSafeSlider;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "scroll-safe-slider": LocalJSX.ScrollSafeSlider & JSXBase.HTMLAttributes<HTMLScrollSafeSliderElement>;
        }
    }
}
